---
title: "TF transcriptional waves and pathway analysis"
author: "Cong"
date: "2024-06-28"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: true
    toc_depth: 3
    number_sections: true
    theme: lumen
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# import packages and functions
```{r import packages and functions}
suppressMessages(library(data.table))
suppressMessages(library(ggplot2))
suppressMessages(library(ggforce))
suppressMessages(library(dplyr))

suppressMessages(library(clusterProfiler))
suppressMessages(library(org.Mm.eg.db))
suppressMessages(library(enrichplot))
suppressMessages(library(xlsx))
suppressMessages(library(pheatmap))

set.seed(42)
fl.sources <- list.files("../../scripts/utils/", full.names = T)
tmp <- sapply(fl.sources,source)
```

# import data
```{r import data}
clusterNo <- 7
Data_normed <- read.csv("pagerank.csv", row.names = 1)
group_sorted <- read.table('group_file.txt',header = T, row.names = 1)
group_sorted$oldName <- rownames(group_sorted)
rownames(group_sorted) <- group_sorted$newName
wavedf <- data.frame(x = c(1,2,2,3,3,4,4,5,5), 
                     y = c(3,5,1,3,1,3,0,4,2),
                     samplename = c("Naive","TE","TexProg","MP","TexInt","TRM","TexTerm","TEM","TCM"),
                     labelposx = c(1,2,2,3,3,4,4,5,5),
                     labelposy = c(3,5,1,3,1.4,3,0,4,2)-0.4)
df2 <- read.csv("cluster_result.csv", row.names = 1)
```

# generate plots

```{r generate wave files}
tmp <- lapply(c(1:clusterNo), function(x) outputWave(x, wavedf, df2, Data_normed, group_sorted))
print(tmp[[1]])

```


# pathway analysis
You can skip this part if you already have enriched pathways. Running this part may take ~10 min.
```{r over-representation GO and KEGG terms}
# L <- list.files(path="./", pattern = "c[0-9]+.txt")
# tmp <- lapply(L, gsea)

```
# selected pathways visualization
```{r}
df <- read.xlsx("SuppFig4 wave GSEA pathways.xlsx", sheetIndex = 1) 
df2 <- df %>% dplyr::select(wave.cluster, Description, p.adjust) %>%
      tidyr::pivot_wider(names_from = wave.cluster, values_from = p.adjust) %>% as.data.frame() %>% replace(is.na(.), 1) %>%
      tibble::column_to_rownames("Description") 
knitr::kable(df[1:6,1:6], caption = "pathways result") |> kableExtra::kable_styling(latex_options = 'scale_down')
knitr::kable(df2[1:6,1:6], caption = "data for visualization") |> kableExtra::kable_styling(latex_options = 'scale_down')
```


```{r heatmap visualization}
cutoff <- 0.05
dt2 <- apply(df2,1:2, function(x) min(x, cutoff)) %>% as.data.frame()

## remove the rows with no variation
dt3 <- dt2[rowSums(dt2)!=cutoff*ncol(dt2),]
print(dim(dt3))
## heatmap
p1 <- pheatmap(dt3, fontsize = 7, show_rownames = T,
                 angle_col = 45, show_colnames = T,
                 cellwidth = 8, cellheight = 8,
                 cluster_rows = T, cluster_cols = T,
                 clustering_distance_rows = "correlation",
                 clustering_distance_cols = "correlation",
                 clustering_method = "average",
                 cutree_rows = 7, 
                 treeheight_row = 10, treeheight_col = 10,
                 border_color = NA,
                 color = colorRampPalette(c("red","blue"))(20))
print(p1)
    
```

```{r save to file}
## save to file
pdf(paste0("hp_transcriptional_waves_selected_pathway_summary_",cutoff,"_max_hclust_cluster.pdf"))
print(p1)
dev.off()

```


# session info
```{r }
sessionInfo()
```

