---
title: "context-dependent TF community analysis"
author: "Cong"
date: "2024-09-03"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: true
    toc_depth: 3
    number_sections: true
    theme: lumen
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# import packages and functions
```{r import packages and functions}
suppressMessages(library(igraph))
suppressMessages(library(ggplot2))
suppressMessages(library(dplyr))
suppressMessages(library(RColorBrewer))
suppressMessages(library(clusterProfiler))
suppressMessages(library(org.Mm.eg.db))
suppressMessages(library(enrichplot))
suppressMessages(library(xlsx))

set.seed(42)
fl.sources <- list.files("../../scripts/utils/", full.names = T)
tmp <- sapply(fl.sources,source)
```

# load two networks first
```{r}
g1 <- readRDS('graph_shrinkage_res0.9_s0.15_TexTerm_subset_TFs_v2.rds')
g2 <- readRDS('graph_shrinkage_res0.9_s0.15_TRM_subset_TFs_v2.rds')
gv1 <- igraph::as_data_frame(g1, "vertices")
gv2 <- igraph::as_data_frame(g2, "vertices")

common_tfs <- intersect(gv1$name, gv2$name)
tex_tfs <- setdiff(gv1$name, gv2$name)
trm_tfs <- setdiff(gv2$name, gv1$name)

```
# community membership extraction
```{r}
lapply(unique(gv1$cluster), function(x) writeLines(gv1[gv1$cluster==x,'name'],paste0('tex_cluster_',x,'.txt')))
lapply(unique(gv2$cluster), function(x) writeLines(gv2[gv2$cluster==x,'name'],paste0('trm_cluster_',x,'.txt')))

```

# gsea analysis 
```{r}
L <- list.files(path="./", pattern = "cluster_[0-9]+.txt")
lapply(L, function(x) gsea(x=x, output_file = 'summary_cluster_GO_KEGG.xlsx'))

```


# session info
```{r }
sessionInfo()
```

